/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lecturer;

/**
 *
 * @author PC
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App(String title) {
        super(title);
        initComponents();
        initDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        iconAvatar = new javax.swing.JLabel();
        iconMenu = new javax.swing.JLabel();
        iconLogo = new javax.swing.JLabel();
        labelBranchName = new javax.swing.JLabel();
        iconNotification = new javax.swing.JLabel();
        iconAddCourse = new javax.swing.JLabel();
        panelSidebar = new javax.swing.JPanel();
        labelCopyright = new javax.swing.JLabel();
        tabDashboard = new javax.swing.JPanel();
        labelDashboard = new javax.swing.JLabel();
        tabCourses = new javax.swing.JPanel();
        labelCourses = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        panelDashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCourses = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        panelHeader.setBackground(new java.awt.Color(153, 153, 255));

        iconAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturer/icons/avatar_female.png"))); // NOI18N
        iconAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        iconMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturer/icons/menu.png"))); // NOI18N
        iconMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMenuMouseClicked(evt);
            }
        });

        iconLogo.setForeground(new java.awt.Color(255, 255, 255));
        iconLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturer/icons/logo.png"))); // NOI18N
        iconLogo.setToolTipText("");
        iconLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelBranchName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelBranchName.setForeground(new java.awt.Color(255, 255, 255));
        labelBranchName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBranchName.setText("ONLINE COURSE MANAGEMENT SYSTEM");
        labelBranchName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        iconNotification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturer/icons/notification.png"))); // NOI18N
        iconNotification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        iconAddCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAddCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturer/icons/add_course.png"))); // NOI18N
        iconAddCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                .addComponent(iconAddCourse)
                .addGap(10, 10, 10)
                .addComponent(iconNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(iconAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconLogo)
                    .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconAvatar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconNotification, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconAddCourse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconMenu, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        panelSidebar.setBackground(new java.awt.Color(153, 153, 255));
        panelSidebar.setAutoscrolls(true);

        labelCopyright.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCopyright.setForeground(new java.awt.Color(255, 255, 255));
        labelCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCopyright.setText("© 2020 JByNine");

        tabDashboard.setBackground(new java.awt.Color(153, 153, 255));
        tabDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabDashboardMouseClicked(evt);
            }
        });

        labelDashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDashboard.setForeground(new java.awt.Color(255, 255, 255));
        labelDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturer/icons/dashboard.png"))); // NOI18N
        labelDashboard.setText("DASHBOARD");
        labelDashboard.setIconTextGap(10);

        javax.swing.GroupLayout tabDashboardLayout = new javax.swing.GroupLayout(tabDashboard);
        tabDashboard.setLayout(tabDashboardLayout);
        tabDashboardLayout.setHorizontalGroup(
            tabDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabDashboardLayout.setVerticalGroup(
            tabDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        tabCourses.setBackground(new java.awt.Color(153, 153, 255));
        tabCourses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCoursesMouseClicked(evt);
            }
        });

        labelCourses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCourses.setForeground(new java.awt.Color(255, 255, 255));
        labelCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturer/icons/courses.png"))); // NOI18N
        labelCourses.setText("COURSES");
        labelCourses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCourses.setIconTextGap(10);

        javax.swing.GroupLayout tabCoursesLayout = new javax.swing.GroupLayout(tabCourses);
        tabCourses.setLayout(tabCoursesLayout);
        tabCoursesLayout.setHorizontalGroup(
            tabCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCoursesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabCoursesLayout.setVerticalGroup(
            tabCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCourses, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCopyright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tabDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 491, Short.MAX_VALUE)
                .addComponent(labelCopyright)
                .addGap(15, 15, 15))
        );

        panelBody.setBackground(new java.awt.Color(204, 204, 255));

        panelDashboard.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 590, Short.MAX_VALUE))
        );

        panelCourses.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Courses");

        javax.swing.GroupLayout panelCoursesLayout = new javax.swing.GroupLayout(panelCourses);
        panelCourses.setLayout(panelCoursesLayout);
        panelCoursesLayout.setHorizontalGroup(
            panelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        panelCoursesLayout.setVerticalGroup(
            panelCoursesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoursesLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 578, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCourses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMenuMouseClicked
        if (panelSidebar.isVisible())
            panelSidebar.setVisible(false);
        else
            panelSidebar.setVisible(true);
    }//GEN-LAST:event_iconMenuMouseClicked

    private void tabDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDashboardMouseClicked
        tabDashboard.setBackground(panelBody.getBackground());
        tabCourses.setBackground(panelSidebar.getBackground());
        panelDashboard.setVisible(true);
        panelCourses.setVisible(false);
    }//GEN-LAST:event_tabDashboardMouseClicked

    private void tabCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCoursesMouseClicked
        tabDashboard.setBackground(panelSidebar.getBackground());
        tabCourses.setBackground(panelBody.getBackground());
        panelDashboard.setVisible(false);
        panelCourses.setVisible(true);
    }//GEN-LAST:event_tabCoursesMouseClicked

    private void initDisplay() {
        tabDashboard.setBackground(panelBody.getBackground());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App("JCM - Online Course Management System - JByNine").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconAddCourse;
    private javax.swing.JLabel iconAvatar;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel iconMenu;
    private javax.swing.JLabel iconNotification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelBranchName;
    private javax.swing.JLabel labelCopyright;
    private javax.swing.JLabel labelCourses;
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelCourses;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel tabCourses;
    private javax.swing.JPanel tabDashboard;
    // End of variables declaration//GEN-END:variables
}
