/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.auth;

import ui.student.StudentApp;
import ui.teacher.TeacherApp;

/**
 *
 * @author JByNine
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JPanel();
        LogoImg = new javax.swing.JLabel();
        LogoName = new javax.swing.JLabel();
        SignUpForm = new javax.swing.JPanel();
        labelSignUp = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelConfirmPassword = new javax.swing.JLabel();
        isTeacher = new javax.swing.JRadioButton();
        requestSignIn = new javax.swing.JLabel();
        usernamePane = new javax.swing.JPanel();
        usernameIcon = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        passwordPane = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        passwordIcon = new javax.swing.JLabel();
        confirmPasswordPane = new javax.swing.JPanel();
        confirmPassword = new javax.swing.JPasswordField();
        confirmPasswordIcon = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        signIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JCM Sign Up");
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setName("signUpFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        Logo.setBackground(new java.awt.Color(46, 81, 133));
        Logo.setPreferredSize(new java.awt.Dimension(600, 600));

        LogoImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/auth/assets/online-course.png"))); // NOI18N
        LogoImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LogoName.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        LogoName.setForeground(new java.awt.Color(255, 255, 255));
        LogoName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoName.setText("JCM - Courses Management System");
        LogoName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LogoImg))
            .addComponent(LogoName, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoImg)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(LogoName))
        );

        SignUpForm.setBackground(new java.awt.Color(191, 220, 255));
        SignUpForm.setPreferredSize(new java.awt.Dimension(400, 600));

        labelSignUp.setFont(labelSignUp.getFont().deriveFont(labelSignUp.getFont().getStyle() | java.awt.Font.BOLD, 31));
        labelSignUp.setText("Sign up");

        labelUsername.setFont(labelUsername.getFont().deriveFont((float)18));
        labelUsername.setLabelFor(username);
        labelUsername.setText("Username");

        labelPassword.setFont(labelPassword.getFont().deriveFont((float)18));
        labelPassword.setLabelFor(password);
        labelPassword.setText("Password");

        labelConfirmPassword.setFont(labelConfirmPassword.getFont().deriveFont((float)18));
        labelConfirmPassword.setLabelFor(confirmPassword);
        labelConfirmPassword.setText("Confirm password");

        isTeacher.setBackground(new java.awt.Color(191, 220, 255));
        isTeacher.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        isTeacher.setText("Teacher");

        requestSignIn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        requestSignIn.setText("Already have a JCM account?");

        usernamePane.setBackground(new java.awt.Color(191, 217, 255));
        usernamePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usernamePaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usernamePaneMouseExited(evt);
            }
        });

        usernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/auth/assets/user.png"))); // NOI18N
        usernameIcon.setToolTipText("");
        usernameIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usernameIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usernameIconMouseExited(evt);
            }
        });

        username.setBackground(new java.awt.Color(191, 217, 255));
        username.setFont(username.getFont().deriveFont((float)18));
        username.setText("johnDoe");
        username.setToolTipText("");
        username.setBorder(null);
        username.setName("username"); // NOI18N
        username.setSelectionColor(new java.awt.Color(46, 81, 133));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usernameMouseExited(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usernamePaneLayout = new javax.swing.GroupLayout(usernamePane);
        usernamePane.setLayout(usernamePaneLayout);
        usernamePaneLayout.setHorizontalGroup(
            usernamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usernamePaneLayout.createSequentialGroup()
                .addComponent(usernameIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        usernamePaneLayout.setVerticalGroup(
            usernamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePaneLayout.createSequentialGroup()
                .addGroup(usernamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameIcon))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        passwordPane.setBackground(new java.awt.Color(191, 217, 255));
        passwordPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordPaneMouseExited(evt);
            }
        });

        password.setBackground(new java.awt.Color(191, 217, 255));
        password.setFont(password.getFont().deriveFont((float)18));
        password.setText("password");
        password.setBorder(null);
        password.setName("password"); // NOI18N
        password.setSelectionColor(new java.awt.Color(46, 81, 133));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordMouseExited(evt);
            }
        });

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/auth/assets/padlock.png"))); // NOI18N
        passwordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout passwordPaneLayout = new javax.swing.GroupLayout(passwordPane);
        passwordPane.setLayout(passwordPaneLayout);
        passwordPaneLayout.setHorizontalGroup(
            passwordPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPaneLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(passwordIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        passwordPaneLayout.setVerticalGroup(
            passwordPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPaneLayout.createSequentialGroup()
                .addGroup(passwordPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordIcon)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        confirmPasswordPane.setBackground(new java.awt.Color(191, 217, 255));
        confirmPasswordPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmPasswordPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmPasswordPaneMouseExited(evt);
            }
        });

        confirmPassword.setBackground(new java.awt.Color(191, 217, 255));
        confirmPassword.setFont(confirmPassword.getFont().deriveFont((float)18));
        confirmPassword.setText("password");
        confirmPassword.setBorder(null);
        confirmPassword.setName("password"); // NOI18N
        confirmPassword.setSelectionColor(new java.awt.Color(46, 81, 133));
        confirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPasswordFocusLost(evt);
            }
        });
        confirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmPasswordMouseExited(evt);
            }
        });

        confirmPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/auth/assets/padlock.png"))); // NOI18N
        confirmPasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmPasswordIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmPasswordIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout confirmPasswordPaneLayout = new javax.swing.GroupLayout(confirmPasswordPane);
        confirmPasswordPane.setLayout(confirmPasswordPaneLayout);
        confirmPasswordPaneLayout.setHorizontalGroup(
            confirmPasswordPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmPasswordPaneLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(confirmPasswordIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        confirmPasswordPaneLayout.setVerticalGroup(
            confirmPasswordPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmPasswordPaneLayout.createSequentialGroup()
                .addGroup(confirmPasswordPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmPasswordIcon)
                    .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        btnSignUp.setBackground(new java.awt.Color(147, 186, 243));
        btnSignUp.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSignUp.setForeground(java.awt.Color.white);
        btnSignUp.setText("Sign in");
        btnSignUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 217, 255), 1, true));
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        signIn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        signIn.setForeground(java.awt.Color.blue);
        signIn.setText("Sign in");
        signIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SignUpFormLayout = new javax.swing.GroupLayout(SignUpForm);
        SignUpForm.setLayout(SignUpFormLayout);
        SignUpFormLayout.setHorizontalGroup(
            SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(labelSignUp))
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelUsername))
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(usernamePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelPassword))
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(confirmPasswordPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelConfirmPassword))
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(passwordPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(isTeacher))
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(requestSignIn)
                .addGap(1, 1, 1)
                .addComponent(signIn))
        );
        SignUpFormLayout.setVerticalGroup(
            SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(labelUsername)
                .addGap(8, 8, 8)
                .addComponent(usernamePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(labelPassword)
                .addGap(8, 8, 8)
                .addComponent(confirmPasswordPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(labelConfirmPassword)
                .addGap(8, 8, 8)
                .addComponent(passwordPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(isTeacher)
                .addGap(7, 7, 7)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requestSignIn)
                    .addComponent(signIn)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(SignUpForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignUpForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameIconMouseEntered
        // TODO add your handling code here:
        usernamePane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_usernameIconMouseEntered

    private void usernameIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameIconMouseExited
        // TODO add your handling code here:
        usernamePane.setBorder(null);
    }//GEN-LAST:event_usernameIconMouseExited

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        usernamePane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        usernamePane.setBorder(null);
    }//GEN-LAST:event_usernameFocusLost

    private void usernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseEntered
        // TODO add your handling code here:
        usernamePane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_usernameMouseEntered

    private void usernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseExited
        // TODO add your handling code here:
        usernamePane.setBorder(null);
    }//GEN-LAST:event_usernameMouseExited

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernamePaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernamePaneMouseEntered
        // TODO add your handling code here:
        usernamePane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_usernamePaneMouseEntered

    private void usernamePaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernamePaneMouseExited
        // TODO add your handling code here:
        usernamePane.setBorder(null);
    }//GEN-LAST:event_usernamePaneMouseExited

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        passwordPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        passwordPane.setBorder(null);
    }//GEN-LAST:event_passwordFocusLost

    private void passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseEntered
        // TODO add your handling code here:
        passwordPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_passwordMouseEntered

    private void passwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseExited
        // TODO add your handling code here:
        passwordPane.setBorder(null);
    }//GEN-LAST:event_passwordMouseExited

    private void passwordIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordIconMouseEntered
        // TODO add your handling code here:
        passwordPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_passwordIconMouseEntered

    private void passwordIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordIconMouseExited
        // TODO add your handling code here:
        passwordPane.setBorder(null);
    }//GEN-LAST:event_passwordIconMouseExited

    private void passwordPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordPaneMouseEntered
        // TODO add your handling code here:
        passwordPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_passwordPaneMouseEntered

    private void passwordPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordPaneMouseExited
        // TODO add your handling code here:
        passwordPane.setBorder(null);
    }//GEN-LAST:event_passwordPaneMouseExited

    private void confirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordFocusGained
        // TODO add your handling code here:
        confirmPasswordPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_confirmPasswordFocusGained

    private void confirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordFocusLost
        // TODO add your handling code here:
        confirmPasswordPane.setBorder(null);
    }//GEN-LAST:event_confirmPasswordFocusLost

    private void confirmPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPasswordMouseEntered
        // TODO add your handling code here:
        confirmPasswordPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_confirmPasswordMouseEntered

    private void confirmPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPasswordMouseExited
        // TODO add your handling code here:
        confirmPasswordPane.setBorder(null);
    }//GEN-LAST:event_confirmPasswordMouseExited

    private void confirmPasswordIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPasswordIconMouseEntered
        // TODO add your handling code here:
        passwordPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_confirmPasswordIconMouseEntered

    private void confirmPasswordIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPasswordIconMouseExited
        // TODO add your handling code here:
        passwordPane.setBorder(null);
    }//GEN-LAST:event_confirmPasswordIconMouseExited

    private void confirmPasswordPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPasswordPaneMouseEntered
        // TODO add your handling code here:
        confirmPasswordPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.lightGray));
    }//GEN-LAST:event_confirmPasswordPaneMouseEntered

    private void confirmPasswordPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPasswordPaneMouseExited
        // TODO add your handling code here:
        confirmPasswordPane.setBorder(null);
    }//GEN-LAST:event_confirmPasswordPaneMouseExited

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        if (isTeacher.isSelected()) {
            new TeacherApp().setVisible(true);
        } else {
            new StudentApp().setVisible(true);
        }
    }//GEN-LAST:event_btnSignUpMouseClicked

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        // TODO add your handling code here:
        btnSignUp.setBackground(new java.awt.Color(46, 81, 133));
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        // TODO add your handling code here:
        btnSignUp.setBackground(new java.awt.Color(147, 186, 243));
    }//GEN-LAST:event_btnSignUpMouseExited

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void signInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new SignIn().setVisible(true);
    }//GEN-LAST:event_signInMouseClicked

    private void signInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInMouseEntered
        // TODO add your handling code here:
        signIn.setFont(new java.awt.Font("Ubuntu", 1, 18));
    }//GEN-LAST:event_signInMouseEntered

    private void signInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInMouseExited
        // TODO add your handling code here:
        signIn.setFont(new java.awt.Font("Ubuntu", 0, 18));
    }//GEN-LAST:event_signInMouseExited

    public void run() {
        this.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logo;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JLabel LogoName;
    private javax.swing.JPanel SignUpForm;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JLabel confirmPasswordIcon;
    private javax.swing.JPanel confirmPasswordPane;
    private javax.swing.JRadioButton isTeacher;
    private javax.swing.JLabel labelConfirmPassword;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelSignUp;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JPanel passwordPane;
    private javax.swing.JLabel requestSignIn;
    private javax.swing.JLabel signIn;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameIcon;
    private javax.swing.JPanel usernamePane;
    // End of variables declaration//GEN-END:variables
}
