/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auth;

/**
 *
 * @author JByNine
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JPanel();
        LogoImg = new javax.swing.JLabel();
        LogoName = new javax.swing.JLabel();
        SignUpForm = new javax.swing.JPanel();
        labelSignUp = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelConfirmPassword = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JCM Sign Up");
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setName("signUpFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        Logo.setBackground(new java.awt.Color(46, 81, 133));
        Logo.setPreferredSize(new java.awt.Dimension(600, 600));
        Logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auth/online-course.png"))); // NOI18N
        LogoImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logo.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        LogoName.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        LogoName.setForeground(new java.awt.Color(255, 255, 255));
        LogoName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoName.setText("JCM - Courses Management System");
        LogoName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logo.add(LogoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 600, -1));

        SignUpForm.setBackground(new java.awt.Color(191, 220, 255));
        SignUpForm.setPreferredSize(new java.awt.Dimension(400, 600));
        SignUpForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSignUp.setFont(labelSignUp.getFont().deriveFont(labelSignUp.getFont().getStyle() | java.awt.Font.BOLD, 31));
        labelSignUp.setText("Sign up");
        SignUpForm.add(labelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 40));

        labelUsername.setFont(labelUsername.getFont().deriveFont((float)18));
        labelUsername.setLabelFor(username);
        labelUsername.setText("Username");
        SignUpForm.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        labelPassword.setFont(labelPassword.getFont().deriveFont((float)18));
        labelPassword.setLabelFor(password);
        labelPassword.setText("Password");
        SignUpForm.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        labelConfirmPassword.setFont(labelConfirmPassword.getFont().deriveFont((float)18));
        labelConfirmPassword.setLabelFor(confirmPassword);
        labelConfirmPassword.setText("Confirm password");
        SignUpForm.add(labelConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        username.setFont(username.getFont().deriveFont((float)18));
        username.setText("username");
        username.setName("username"); // NOI18N
        username.setSelectedTextColor(java.awt.Color.darkGray);
        username.setSelectionColor(new java.awt.Color(153, 153, 255));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        SignUpForm.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 340, 50));

        password.setFont(password.getFont().deriveFont((float)18));
        password.setText("password");
        password.setName("password"); // NOI18N
        password.setSelectedTextColor(java.awt.Color.darkGray);
        password.setSelectionColor(new java.awt.Color(153, 153, 255));
        SignUpForm.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 340, 50));

        confirmPassword.setFont(confirmPassword.getFont().deriveFont((float)18));
        confirmPassword.setText("confirmPassword");
        confirmPassword.setName("confirmPassword"); // NOI18N
        confirmPassword.setSelectedTextColor(java.awt.Color.darkGray);
        confirmPassword.setSelectionColor(new java.awt.Color(153, 153, 255));
        SignUpForm.add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 340, 50));

        btnSignUp.setBackground(new java.awt.Color(46, 81, 133));
        btnSignUp.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        SignUpForm.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(SignUpForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SignUpForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    public void run() {
        this.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logo;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JLabel LogoName;
    private javax.swing.JPanel SignUpForm;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JLabel labelConfirmPassword;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelSignUp;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
